name: build and push image

on:
    push:
        branches:
            - main

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --no-cache-dir .
            
            - name: Check Streamlit app syntax
              run: |
                python -c "import streamlit; print('Streamlit syntax check passed')"

        
    deploy:
        needs: Build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        
        steps:
        - name: Deploy to Streamlit Cloud
          run: |
            echo "App will be automatically deployed to Streamlit Cloud"
            echo "Make sure your app is connected to Streamlit Cloud"